### PR TITLE
Add script for npm start.

### PR DESCRIPTION
**Pull request by euroclydon37**
I thought it would be nice to have a convenient `npm start` for everyone. It does the following.
1. Creates a `.env` file with the silly defaults from the README if you don't already have one.
2. Runs `npm run build`.
3. Runs `node ./build/server/gamenode`

### CODE REVIEW

**Comment by AMMayberry1** [comment]
Hey thanks for the PR! Could you ping me (Veld) in the karabast discord so we can get you added to the dev chat?

**Comment by euroclydon37** [comment]
@AMMayberry1 Done! Happy to contribute.

**Comment by danbastin** [comment]
Looks good to me! I've been meaning to add a command for this and getting the basic env setup for locval dev is great.

**Comment by danbastin** [comment]
Actually, can we have this be under "dev" just to maintain consistency with the fronted which uses `npm run dev` to start the dev environement?

**Review by AMMayberry1 — APPROVED** [review]

**Pull request merged**
